[project]
name = "prisma-python-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "prisma>=0.15.0",
    "pydantic[email]>=2.11.7",
    "uvicorn[standard]>=0.34.3",
]
